/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import connectDB.ConnectDB;
import dao.NhanVienHanhChinh_DAO;
import dao.TaiKhoan_DAO;
import entity.NhanVienHanhChinh;
import entity.TaiKhoan;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.Random;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.activation.DataHandler;
import javax.activation.DataSource;

/**
 *
 * @author vuhai
 */
public class GDLogin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private final String email = "namhaivu06012003@gmail.com";
    private final String emailPass = "lnaw iimk noxw ifoo";

    public GDLogin() {

        initComponents();
        this.setTitle("Chương trình quản lý lương của công ty Thịnh Vượng.");
        icon();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(3);

        try {
            ConnectDB.getInstance().connect();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void icon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameNhapMKMoi = new javax.swing.JFrame();
        jButtonXacNhan = new javax.swing.JButton();
        jPasswordFieldXacNhanMK = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldMKMoi = new javax.swing.JPasswordField();
        jLabelThongBaoDoiMK = new javax.swing.JLabel();
        jFrameGuiEmail = new javax.swing.JFrame();
        jButtonQuayLai = new javax.swing.JButton();
        jLabelTenDN = new javax.swing.JLabel();
        jLabelTenCty = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTenDN = new javax.swing.JTextField();
        jButtonGuiEmail = new javax.swing.JButton();
        jLabelThongBanTK = new javax.swing.JLabel();
        jFrameNhapMaXacNhan = new javax.swing.JFrame();
        jButtonQuayLai2 = new javax.swing.JButton();
        jLabelTenDN2 = new javax.swing.JLabel();
        jLabelTenCty2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldMaXacNhan = new javax.swing.JTextField();
        jButtonXacNhanMa = new javax.swing.JButton();
        jLabelThongBanMa = new javax.swing.JLabel();
        jButtonDangNhap = new javax.swing.JButton();
        jButtonQuenMatKhau = new javax.swing.JButton();
        jTextFieldTenTK = new javax.swing.JTextField();
        jPasswordFieldMatKhau = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelThongBaoSaiMK = new javax.swing.JLabel();

        jFrameNhapMKMoi.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonXacNhan.setBackground(new java.awt.Color(85, 167, 222));
        jButtonXacNhan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXacNhan.setText("Xác nhận");
        jButtonXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXacNhanActionPerformed(evt);
            }
        });

        jPasswordFieldXacNhanMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldXacNhanMKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPasswordFieldXacNhanMKMouseReleased(evt);
            }
        });
        jPasswordFieldXacNhanMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldXacNhanMKActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Xác nhận mật khẩu:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nhập mật khẩu mới:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("CÔNG TY TNHH MAY MẶC THỊNH VƯỢNG");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N

        jPasswordFieldMKMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldMKMoiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPasswordFieldMKMoiMouseReleased(evt);
            }
        });
        jPasswordFieldMKMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldMKMoiActionPerformed(evt);
            }
        });

        jLabelThongBaoDoiMK.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelThongBaoDoiMK.setForeground(new java.awt.Color(255, 0, 51));
        jLabelThongBaoDoiMK.setText("                                 ");

        javax.swing.GroupLayout jFrameNhapMKMoiLayout = new javax.swing.GroupLayout(jFrameNhapMKMoi.getContentPane());
        jFrameNhapMKMoi.getContentPane().setLayout(jFrameNhapMKMoiLayout);
        jFrameNhapMKMoiLayout.setHorizontalGroup(
            jFrameNhapMKMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameNhapMKMoiLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jFrameNhapMKMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameNhapMKMoiLayout.createSequentialGroup()
                        .addGroup(jFrameNhapMKMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jFrameNhapMKMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldXacNhanMK, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameNhapMKMoiLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameNhapMKMoiLayout.createSequentialGroup()
                        .addComponent(jButtonXacNhan)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameNhapMKMoiLayout.createSequentialGroup()
                        .addComponent(jLabelThongBaoDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jFrameNhapMKMoiLayout.setVerticalGroup(
            jFrameNhapMKMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameNhapMKMoiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addGroup(jFrameNhapMKMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordFieldMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameNhapMKMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldXacNhanMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelThongBaoDoiMK)
                .addGap(8, 8, 8)
                .addComponent(jButtonXacNhan)
                .addGap(68, 68, 68))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrameGuiEmail.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonQuayLai.setBackground(new java.awt.Color(85, 167, 222));
        jButtonQuayLai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuayLai.setText("Quay lại");
        jButtonQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuayLaiActionPerformed(evt);
            }
        });

        jLabelTenDN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTenDN.setText("Nhập tên đăng nhập:");

        jLabelTenCty.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTenCty.setText("CÔNG TY TNHH MAY MẶC THỊNH VƯỢNG");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N

        jTextFieldTenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTenDNActionPerformed(evt);
            }
        });

        jButtonGuiEmail.setBackground(new java.awt.Color(85, 167, 222));
        jButtonGuiEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonGuiEmail.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuiEmail.setText("Gửi email");
        jButtonGuiEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuiEmailActionPerformed(evt);
            }
        });

        jLabelThongBanTK.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelThongBanTK.setForeground(new java.awt.Color(255, 0, 51));
        jLabelThongBanTK.setText("                                 ");

        javax.swing.GroupLayout jFrameGuiEmailLayout = new javax.swing.GroupLayout(jFrameGuiEmail.getContentPane());
        jFrameGuiEmail.getContentPane().setLayout(jFrameGuiEmailLayout);
        jFrameGuiEmailLayout.setHorizontalGroup(
            jFrameGuiEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameGuiEmailLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jFrameGuiEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameGuiEmailLayout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(jFrameGuiEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTenDN)
                            .addComponent(jLabelTenCty)
                            .addGroup(jFrameGuiEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelThongBanTK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldTenDN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(jFrameGuiEmailLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButtonQuayLai)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonGuiEmail)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jFrameGuiEmailLayout.setVerticalGroup(
            jFrameGuiEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameGuiEmailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTenCty)
                .addGap(18, 18, 18)
                .addComponent(jLabelTenDN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabelThongBanTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameGuiEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuayLai)
                    .addComponent(jButtonGuiEmail))
                .addGap(102, 102, 102))
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrameNhapMaXacNhan.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonQuayLai2.setBackground(new java.awt.Color(85, 167, 222));
        jButtonQuayLai2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonQuayLai2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuayLai2.setText("Quay lại");
        jButtonQuayLai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuayLai2ActionPerformed(evt);
            }
        });

        jLabelTenDN2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTenDN2.setText("Nhập mã xác nhận:");

        jLabelTenCty2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTenCty2.setText("CÔNG TY TNHH MAY MẶC THỊNH VƯỢNG");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N

        jTextFieldMaXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaXacNhanActionPerformed(evt);
            }
        });

        jButtonXacNhanMa.setBackground(new java.awt.Color(85, 167, 222));
        jButtonXacNhanMa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonXacNhanMa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXacNhanMa.setText("Xác nhận");
        jButtonXacNhanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXacNhanMaActionPerformed(evt);
            }
        });

        jLabelThongBanMa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelThongBanMa.setForeground(new java.awt.Color(255, 0, 51));
        jLabelThongBanMa.setText("                                 ");

        javax.swing.GroupLayout jFrameNhapMaXacNhanLayout = new javax.swing.GroupLayout(jFrameNhapMaXacNhan.getContentPane());
        jFrameNhapMaXacNhan.getContentPane().setLayout(jFrameNhapMaXacNhanLayout);
        jFrameNhapMaXacNhanLayout.setHorizontalGroup(
            jFrameNhapMaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameNhapMaXacNhanLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jFrameNhapMaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameNhapMaXacNhanLayout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(jFrameNhapMaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTenDN2)
                            .addComponent(jLabelTenCty2)
                            .addGroup(jFrameNhapMaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelThongBanMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldMaXacNhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(jFrameNhapMaXacNhanLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButtonQuayLai2)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonXacNhanMa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jFrameNhapMaXacNhanLayout.setVerticalGroup(
            jFrameNhapMaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameNhapMaXacNhanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTenCty2)
                .addGap(18, 18, 18)
                .addComponent(jLabelTenDN2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMaXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabelThongBanMa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameNhapMaXacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuayLai2)
                    .addComponent(jButtonXacNhanMa))
                .addGap(102, 102, 102))
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButtonDangNhap.setBackground(new java.awt.Color(85, 167, 222));
        jButtonDangNhap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDangNhap.setMnemonic('L');
        jButtonDangNhap.setText("Đăng nhập");
        jButtonDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangNhapActionPerformed(evt);
            }
        });

        jButtonQuenMatKhau.setBackground(new java.awt.Color(85, 167, 222));
        jButtonQuenMatKhau.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuenMatKhau.setMnemonic('F');
        jButtonQuenMatKhau.setText("Quên mật khẩu");
        jButtonQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuenMatKhauActionPerformed(evt);
            }
        });

        jTextFieldTenTK.setText("thinh");
        jTextFieldTenTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTenTKActionPerformed(evt);
            }
        });

        jPasswordFieldMatKhau.setText("1111");
        jPasswordFieldMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldMatKhauMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPasswordFieldMatKhauMouseReleased(evt);
            }
        });
        jPasswordFieldMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldMatKhauActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Tên tài khoản:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Mật khẩu:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("CÔNG TY TNHH MAY MẶC THỊNH VƯỢNG");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N

        jLabelThongBaoSaiMK.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelThongBaoSaiMK.setForeground(new java.awt.Color(255, 0, 51));
        jLabelThongBaoSaiMK.setText("                                 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonDangNhap)
                                .addGap(36, 36, 36)
                                .addComponent(jButtonQuenMatKhau)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelThongBaoSaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTenTK)
                                    .addComponent(jPasswordFieldMatKhau)))
                            .addComponent(jLabel3))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelThongBaoSaiMK)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuenMatKhau)
                    .addComponent(jButtonDangNhap))
                .addGap(75, 75, 75))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangNhapActionPerformed
        // TODO add your handling code here:
        isValid = false;
        nvhc_dao = new NhanVienHanhChinh_DAO();
        tkdao = new TaiKhoan_DAO();
        dsnv = nvhc_dao.getAllNhanVien();
        dstk = tkdao.getAllTaiKhoan();
        String tenTK = jTextFieldTenTK.getText().trim();
        String matKhau = jPasswordFieldMatKhau.getText().trim();
        for (TaiKhoan tk : dstk) {
            if (tk.getTenTK().equalsIgnoreCase(tenTK) && tk.getMatKhau().equalsIgnoreCase(matKhau)) {
                isValid = true;
                nvLog = nvhc_dao.getNhanVienTheoMa(tk.getNv().getMaNV());
            }
        }
        if (isValid) {
            this.dispose();
        } else {
            jLabelThongBaoSaiMK.setText("Tên tài khoản hoặc mật khẩu không chính xác");
        }
    }//GEN-LAST:event_jButtonDangNhapActionPerformed

    private void jPasswordFieldMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldMatKhauActionPerformed
        // TODO add your handling code here:
        jButtonDangNhap.doClick();
    }//GEN-LAST:event_jPasswordFieldMatKhauActionPerformed

    private void jPasswordFieldXacNhanMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldXacNhanMKActionPerformed
        // TODO add your handling code here:
        jButtonXacNhan.doClick();
    }//GEN-LAST:event_jPasswordFieldXacNhanMKActionPerformed

    private void jPasswordFieldMKMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldMKMoiActionPerformed
        // TODO add your handling code here:
        jPasswordFieldXacNhanMK.requestFocus();
    }//GEN-LAST:event_jPasswordFieldMKMoiActionPerformed

    private void jButtonQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuayLaiActionPerformed
        // TODO add your handling code here:
        jFrameGuiEmail.dispose();
    }//GEN-LAST:event_jButtonQuayLaiActionPerformed

    private void jButtonQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuenMatKhauActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrameGuiEmail.setMinimumSize(new Dimension(800, 300));
        jFrameGuiEmail.setVisible(true);
        jFrameGuiEmail.setLocationRelativeTo(null);
        jFrameGuiEmail.setResizable(false);
        jFrameGuiEmail.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/logo.png")));
        jFrameGuiEmail.setDefaultCloseOperation(EXIT_ON_CLOSE);
        jTextFieldTenDN.setText(jTextFieldTenTK.getText());
        jFrameGuiEmail.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void windowClosing(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void windowClosed(WindowEvent e) {
//                JOptionPane.showMessageDialog(null, email);
                setVisible(true);
            }

            @Override
            public void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        }
        );
    }//GEN-LAST:event_jButtonQuenMatKhauActionPerformed

    private void jTextFieldTenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTenDNActionPerformed
        // TODO add your handling code here:
        jButtonGuiEmail.doClick();
    }//GEN-LAST:event_jTextFieldTenDNActionPerformed

    private void jButtonGuiEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuiEmailActionPerformed
        // TODO add your handling code here:
        tkdao = new TaiKhoan_DAO();
        dstk = tkdao.getAllTaiKhoan();
        String tenDN = jTextFieldTenDN.getText();
        String emailNhan = "";
        Boolean check = false;
        for (TaiKhoan tk : dstk) {
            if (tk.getTenTK().equalsIgnoreCase(tenDN)) {
                emailNhan = tk.getNv().getEmail();
                nvLog = tk.getNv();
                tkLog = tk;
                check = true;
                break;
            }
        }
        if (check) {
            Properties props = new Properties();
            props.put("mail.smtp.host", "smtp.gmail.com"); //smtp host
            props.put("mail.smtp.port", "587");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", "true");

            //create authenticator
            Authenticator authenticator = new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(email, emailPass);
                }
            };

            //Phiên làm việc
            Session session = Session.getInstance(props, authenticator);

            //Tạo 1 tin nhắn
            MimeMessage message = new MimeMessage(session);
            try {
                //Kieu noi dung
                message.addHeader("Content-type", "text/HTML; charset=UTF-8");
                //Ng gui 
                message.setFrom(email);
                //Ng nhan
                message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(emailNhan, false));
                //Tieu de
                message.setSubject("Mã xác nhận đổi mật khẩu của bạn");
                //Quy dinh ngay gui
                message.setSentDate(new Date());
                //Quy dinh email nhan phan hoi
                message.setReplyTo(null);
                //Noi dung
                maXacNhan = generateRandomString(10);
                message.setText(maXacNhan, "UTF-8");

                //Gui email
                Transport.send(message);
            } catch (Exception e) {
            }
            jFrameGuiEmail.setVisible(false);
            jFrameNhapMaXacNhan.setVisible(true);
            jFrameNhapMaXacNhan.setMinimumSize(new Dimension(800, 300));
            jFrameNhapMaXacNhan.setVisible(true);
            jFrameNhapMaXacNhan.setLocationRelativeTo(null);
            jFrameNhapMaXacNhan.setResizable(false);
            jFrameNhapMaXacNhan.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/logo.png")));
            jFrameNhapMaXacNhan.setDefaultCloseOperation(EXIT_ON_CLOSE);
            jFrameNhapMaXacNhan.addWindowListener(new WindowListener() {
                @Override
                public void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowClosing(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    jFrameGuiEmail.setVisible(true);
                }

                @Override
                public void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
            });
        } else {
            jLabelThongBanTK.setText("Không tìm thấy tài khoản của nhân viên");
            jTextFieldTenDN.requestFocus();
            return;
        }
    }//GEN-LAST:event_jButtonGuiEmailActionPerformed

    private void jButtonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanActionPerformed
        // TODO add your handling code here:
        String matKhauMoi = jPasswordFieldMKMoi.getText();
        String xacNhan = jPasswordFieldXacNhanMK.getText();
        if (matKhauMoi.equals(xacNhan)) {
            if (matKhauMoi.equals(tkLog.getMatKhau())) {
                jLabelThongBaoDoiMK.setText("Mật khẩu mới không được trùng với mật khẩu cũ");
                jPasswordFieldMKMoi.requestFocus();
                return;
            } else {
                tkLog.setMatKhau(matKhauMoi);
                tkdao = new TaiKhoan_DAO();
                tkdao.updateTaiKhoan(tkLog);
            }
        } else {
            jLabelThongBaoDoiMK.setText("Mật khẩu xác nhận lại không trùng khớp");
            jPasswordFieldXacNhanMK.requestFocus();
            return;
        }
        jFrameNhapMKMoi.dispose();
    }//GEN-LAST:event_jButtonXacNhanActionPerformed

    private void jButtonQuayLai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuayLai2ActionPerformed
        // TODO add your handling code here:
        jFrameNhapMaXacNhan.dispose();
    }//GEN-LAST:event_jButtonQuayLai2ActionPerformed

    private void jTextFieldMaXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaXacNhanActionPerformed
        // TODO add your handling code here:
        jButtonXacNhanMa.doClick();
    }//GEN-LAST:event_jTextFieldMaXacNhanActionPerformed

    private void jButtonXacNhanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanMaActionPerformed
        // TODO add your handling code here:
        if (jTextFieldMaXacNhan.getText().equals(maXacNhan)) {
            jFrameNhapMaXacNhan.setVisible(false);
            jFrameNhapMKMoi.setVisible(true);
            jFrameNhapMKMoi.setMinimumSize(new Dimension(800, 300));
            jFrameNhapMKMoi.setVisible(true);
            jFrameNhapMKMoi.setLocationRelativeTo(null);
            jFrameNhapMKMoi.setResizable(false);
            jFrameNhapMKMoi.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/logo.png")));
            jFrameNhapMKMoi.setDefaultCloseOperation(EXIT_ON_CLOSE);
            jFrameNhapMKMoi.addWindowListener(new WindowListener() {
                @Override
                public void windowOpened(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowClosing(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowClosed(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    setVisible(true);
                }

                @Override
                public void windowIconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowDeiconified(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowActivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void windowDeactivated(WindowEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
            });
        } else {
            jLabelThongBanMa.setText("Mã xác nhận không chính xác");
            jTextFieldMaXacNhan.requestFocus();
            return;
        }
    }//GEN-LAST:event_jButtonXacNhanMaActionPerformed

    private void jTextFieldTenTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTenTKActionPerformed
        // TODO add your handling code here:
        jPasswordFieldMatKhau.requestFocus();
    }//GEN-LAST:event_jTextFieldTenTKActionPerformed

    private void jPasswordFieldMatKhauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMatKhauMousePressed
        // TODO add your handling code here:
        jPasswordFieldMatKhau.setEchoChar((char) 0);
    }//GEN-LAST:event_jPasswordFieldMatKhauMousePressed

    private void jPasswordFieldMatKhauMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMatKhauMouseReleased
        // TODO add your handling code here:
        jPasswordFieldMatKhau.setEchoChar('*');
    }//GEN-LAST:event_jPasswordFieldMatKhauMouseReleased

    private void jPasswordFieldMKMoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMKMoiMousePressed
        // TODO add your handling code here:
        jPasswordFieldMKMoi.setEchoChar((char) 0);
    }//GEN-LAST:event_jPasswordFieldMKMoiMousePressed

    private void jPasswordFieldMKMoiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMKMoiMouseReleased
        // TODO add your handling code here:
        jPasswordFieldMKMoi.setEchoChar('*');
    }//GEN-LAST:event_jPasswordFieldMKMoiMouseReleased

    private void jPasswordFieldXacNhanMKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldXacNhanMKMousePressed
        // TODO add your handling code here:
        jPasswordFieldXacNhanMK.setEchoChar((char) 0);
    }//GEN-LAST:event_jPasswordFieldXacNhanMKMousePressed

    private void jPasswordFieldXacNhanMKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldXacNhanMKMouseReleased
        // TODO add your handling code here:
        jPasswordFieldXacNhanMK.setEchoChar('*');
    }//GEN-LAST:event_jPasswordFieldXacNhanMKMouseReleased

    public static String generateRandomString(int length) {
        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        Random rng = new Random();
        char[] text = new char[length];
        for (int i = 0; i < length; i++) {
            text[i] = characters.charAt(rng.nextInt(characters.length()));
        }
        return new String(text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDLogin().setVisible(true);
            }
        });
    }

    public NhanVienHanhChinh getCurrNV() {
        return nvLog;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDangNhap;
    private javax.swing.JButton jButtonGuiEmail;
    private javax.swing.JButton jButtonQuayLai;
    private javax.swing.JButton jButtonQuayLai2;
    private javax.swing.JButton jButtonQuenMatKhau;
    private javax.swing.JButton jButtonXacNhan;
    private javax.swing.JButton jButtonXacNhanMa;
    private javax.swing.JFrame jFrameGuiEmail;
    private javax.swing.JFrame jFrameNhapMKMoi;
    private javax.swing.JFrame jFrameNhapMaXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTenCty;
    private javax.swing.JLabel jLabelTenCty2;
    private javax.swing.JLabel jLabelTenDN;
    private javax.swing.JLabel jLabelTenDN2;
    private javax.swing.JLabel jLabelThongBanMa;
    private javax.swing.JLabel jLabelThongBanTK;
    private javax.swing.JLabel jLabelThongBaoDoiMK;
    private javax.swing.JLabel jLabelThongBaoSaiMK;
    private javax.swing.JPasswordField jPasswordFieldMKMoi;
    private javax.swing.JPasswordField jPasswordFieldMatKhau;
    private javax.swing.JPasswordField jPasswordFieldXacNhanMK;
    private javax.swing.JTextField jTextFieldMaXacNhan;
    private javax.swing.JTextField jTextFieldTenDN;
    private javax.swing.JTextField jTextFieldTenTK;
    // End of variables declaration//GEN-END:variables
    private static NhanVienHanhChinh_DAO nvhc_dao;
    private static TaiKhoan_DAO tkdao;
    private static ArrayList<NhanVienHanhChinh> dsnv;
    private static ArrayList<TaiKhoan> dstk;
    private static NhanVienHanhChinh nvLog;
    private static TaiKhoan tkLog;
    private static Boolean isValid = false;
    private static String maXacNhan;

}
