/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.CongNhan_DAO;
import entity.CongNhan;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Date;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class GDQLCongNhan extends javax.swing.JPanel {

    private CongNhan_DAO cn_DAO;
    private DefaultTableModel modelCN;
    private DecimalFormat dfTien = new DecimalFormat();

    private String hinhAnh = "";

    public GDQLCongNhan() {
        cn_DAO = new CongNhan_DAO();
        initComponents();
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(radNu);
        buttonGroup.add(radNam);
         addListCN();
        tableCN.getColumnModel().getColumn(0).setPreferredWidth(40); // stt
        tableCN.getColumnModel().getColumn(1).setPreferredWidth(90); // mã nv
        tableCN.getColumnModel().getColumn(2).setPreferredWidth(120); // họ tên 
        tableCN.getColumnModel().getColumn(4).setPreferredWidth(80); // ngày sinh
        tableCN.getColumnModel().getColumn(5).setPreferredWidth(90); // số điện thoại
        tableCN.getColumnModel().getColumn(6).setPreferredWidth(140); // địa chỉ
        tableCN.getColumnModel().getColumn(7).setPreferredWidth(115);  // tình trạng
        tableCN.getColumnModel().getColumn(8).setPreferredWidth(85); // ngày vào làm
        tableCN.getColumnModel().getColumn(9).setPreferredWidth(95);
        tableCN.getColumnModel().getColumn(10).setPreferredWidth(85); // lương cơ bản
        tableCN.getColumnModel().getColumn(11).setPreferredWidth(120); // chức vụ
        tableCN.getColumnModel().getColumn(12).setPreferredWidth(120);  // email
        tableCN.getColumnModel().getColumn(13).setPreferredWidth(120); // tiền phụ cấp ngày

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pQLCongNhan = new javax.swing.JPanel();
        pTittle = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pTongQuan = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbbLocTinhTrang = new javax.swing.JComboBox<>();
        cbbLocTayNghe = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtTimCN = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        pReload = new javax.swing.JPanel();
        btnReload = new javax.swing.JButton();
        jscrCN = new javax.swing.JScrollPane();
        tableCN = new javax.swing.JTable();
        pImage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbHinhCN = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        pThongTin = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblHoTenNV = new javax.swing.JLabel();
        txtHoTenNV = new javax.swing.JTextField();
        lblPhai = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        lblNgaySinh = new javax.swing.JLabel();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        lblNgayVaoLam = new javax.swing.JLabel();
        dateNgayVaoLam = new com.toedter.calendar.JDateChooser();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        lblPhongBan = new javax.swing.JLabel();
        cbbTayNghe = new javax.swing.JComboBox<>();
        cbbTinhTrang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbbKinhNghiem = new javax.swing.JComboBox<>();
        lblLuongCB = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblTienPhuCapTheoNgay = new javax.swing.JLabel();
        txtTienPhuCapTheoNgay = new javax.swing.JTextField();
        lblTienChuyenCan = new javax.swing.JLabel();
        txtTienChuyenCan = new javax.swing.JTextField();
        lblGhiChu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pQLCongNhan.setBackground(new java.awt.Color(255, 255, 255));
        pQLCongNhan.setPreferredSize(new java.awt.Dimension(958, 735));

        pTittle.setBackground(new java.awt.Color(85, 167, 222));
        pTittle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(233, 231, 231)));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(234, 233, 233));
        jLabel15.setText("QUẢN LÝ CÔNG NHÂN");

        javax.swing.GroupLayout pTittleLayout = new javax.swing.GroupLayout(pTittle);
        pTittle.setLayout(pTittleLayout);
        pTittleLayout.setHorizontalGroup(
            pTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                .addContainerGap())
        );
        pTittleLayout.setVerticalGroup(
            pTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pTongQuan.setBackground(new java.awt.Color(255, 255, 255));
        pTongQuan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(233, 231, 231)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        cbbLocTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm việc", "thôi việc", " " }));
        cbbLocTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLocTinhTrangActionPerformed(evt);
            }
        });

        cbbLocTayNghe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tay nghề", "May vắt sổ", "Cắt vải", "Đóng gói", "May móc xích kép", "May móc xích đơn", "Là ủi" }));
        cbbLocTayNghe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLocTayNgheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbLocTayNghe, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbLocTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbLocTayNghe, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cbbLocTinhTrang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtTimCN.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtTimCN.setForeground(new java.awt.Color(204, 204, 204));
        txtTimCN.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTimCN.setText("Tìm kiếm");
        txtTimCN.setAlignmentY(1.0F);
        txtTimCN.setPreferredSize(new java.awt.Dimension(170, 35));
        txtTimCN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimCNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimCNFocusLost(evt);
            }
        });
        txtTimCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimCNActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(169, 203, 225));
        btnTimKiem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btnTimKiem.setPreferredSize(new java.awt.Dimension(100, 35));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtTimCN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pReload.setBackground(new java.awt.Color(255, 255, 255));

        btnReload.setBackground(new java.awt.Color(85, 167, 222));
        btnReload.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnReload.setMnemonic('R');
        btnReload.setToolTipText("Alt+R");
        btnReload.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.black));
        btnReload.setPreferredSize(new java.awt.Dimension(100, 40));
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pReloadLayout = new javax.swing.GroupLayout(pReload);
        pReload.setLayout(pReloadLayout);
        pReloadLayout.setHorizontalGroup(
            pReloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReloadLayout.createSequentialGroup()
                .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pReloadLayout.setVerticalGroup(
            pReloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReloadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jscrCN.setBackground(new java.awt.Color(255, 255, 255));
        jscrCN.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(0, 102, 102)), "Danh sách công nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jscrCN.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jscrCN.setAutoscrolls(true);

        tableCN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã công nhân", "Họ tên", "Giới tính", "Ngày sinh", "Số điện thoại", "Địa chỉ", "Tay nghề", "Kinh nghiệm", "Tình trạng", "Ngày vào làm", "Tiền phụ cấp ngày", "Tiền chuyên cần", "Ghi chú"
            }
        ));
        tableCN.setToolTipText("");
        tableCN.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableCN.setRowHeight(30);
        tableCN.setShowGrid(true);
        tableCN.setShowVerticalLines(false);
        tableCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCNMouseClicked(evt);
            }
        });
        tableCN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableCNKeyReleased(evt);
            }
        });
        jscrCN.setViewportView(tableCN);

        pImage.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(191, 95, 95));
        jPanel1.setPreferredSize(new java.awt.Dimension(153, 153));

        lbHinhCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHinhCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/none_user.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHinhCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHinhCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnChonAnh.setBackground(new java.awt.Color(85, 167, 222));
        btnChonAnh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnChonAnh.setForeground(new java.awt.Color(255, 255, 255));
        btnChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/camera_32px.png"))); // NOI18N
        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.setEnabled(false);
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pImageLayout = new javax.swing.GroupLayout(pImage);
        pImage.setLayout(pImageLayout);
        pImageLayout.setHorizontalGroup(
            pImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pImageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnChonAnh)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pImageLayout.setVerticalGroup(
            pImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pImageLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(255, 204, 204)), "Thông tin công nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 12))); // NOI18N
        pThongTin.setMaximumSize(new java.awt.Dimension(799, 242));
        pThongTin.setPreferredSize(new java.awt.Dimension(799, 242));
        pThongTin.setRequestFocusEnabled(false);

        lblMaNV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMaNV.setText("Mã nhân viên:");
        lblMaNV.setPreferredSize(new java.awt.Dimension(100, 25));

        txtMaNV.setEditable(false);
        txtMaNV.setBackground(new java.awt.Color(255, 255, 255));
        txtMaNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtMaNV.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMaNV.setPreferredSize(new java.awt.Dimension(100, 25));
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        lblHoTenNV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHoTenNV.setText("Họ tên:");
        lblHoTenNV.setPreferredSize(new java.awt.Dimension(100, 25));

        txtHoTenNV.setEditable(false);
        txtHoTenNV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHoTenNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtHoTenNV.setPreferredSize(new java.awt.Dimension(170, 25));
        txtHoTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenNVActionPerformed(evt);
            }
        });

        lblPhai.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPhai.setText("Giới tính:");
        lblPhai.setPreferredSize(new java.awt.Dimension(100, 25));

        radNam.setBackground(new java.awt.Color(204, 204, 204));
        radNam.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radNam.setText("Nam");
        radNam.setPreferredSize(new java.awt.Dimension(55, 25));
        radNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNamActionPerformed(evt);
            }
        });

        radNu.setBackground(new java.awt.Color(204, 204, 204));
        radNu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radNu.setText("Nữ");
        radNu.setPreferredSize(new java.awt.Dimension(55, 25));
        radNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNuActionPerformed(evt);
            }
        });

        lblNgaySinh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNgaySinh.setText("Ngày sinh:");
        lblNgaySinh.setPreferredSize(new java.awt.Dimension(100, 25));

        dateNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        dateNgaySinh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dateNgaySinh.setAlignmentY(1.0F);
        dateNgaySinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dateNgaySinh.setPreferredSize(new java.awt.Dimension(170, 25));

        lblNgayVaoLam.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNgayVaoLam.setText("Ngày vào làm:");
        lblNgayVaoLam.setPreferredSize(new java.awt.Dimension(100, 25));

        dateNgayVaoLam.setBackground(new java.awt.Color(255, 255, 255));
        dateNgayVaoLam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dateNgayVaoLam.setAlignmentY(1.0F);
        dateNgayVaoLam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dateNgayVaoLam.setPreferredSize(new java.awt.Dimension(170, 25));

        lblSDT.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSDT.setText("Số điện thoại:");
        lblSDT.setPreferredSize(new java.awt.Dimension(100, 25));

        txtSDT.setEditable(false);
        txtSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtSDT.setPreferredSize(new java.awt.Dimension(170, 25));
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtDiaChi.setEditable(false);
        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiaChi.setAlignmentY(1.0F);
        txtDiaChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtDiaChi.setPreferredSize(new java.awt.Dimension(170, 25));
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        lblPhongBan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPhongBan.setText("Tay nghề:");
        lblPhongBan.setPreferredSize(new java.awt.Dimension(90, 25));

        cbbTayNghe.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbbTayNghe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "May vắt sổ", "Cắt vải", "Đóng gói", "May móc xích kép", "May móc xích đơn", "Là ủi" }));
        cbbTayNghe.setEnabled(false);
        cbbTayNghe.setPreferredSize(new java.awt.Dimension(118, 25));
        cbbTayNghe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTayNgheActionPerformed(evt);
            }
        });

        cbbTinhTrang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm việc", "Thôi việc" }));
        cbbTinhTrang.setEnabled(false);
        cbbTinhTrang.setPreferredSize(new java.awt.Dimension(118, 25));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Kinh nghiệm:");
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 25));

        cbbKinhNghiem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbbKinhNghiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 năm", "Dưới 1 năm", "1 năm ", "1.5 năm", "2 năm", "2.5 năm", "3 năm", "3.5 năm", "4 năm", "Trên 4 năm", " " }));
        cbbKinhNghiem.setEnabled(false);
        cbbKinhNghiem.setPreferredSize(new java.awt.Dimension(118, 25));
        cbbKinhNghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKinhNghiemActionPerformed(evt);
            }
        });

        lblLuongCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLuongCB.setText("Tình trạng:");
        lblLuongCB.setPreferredSize(new java.awt.Dimension(105, 25));

        lblDiaChi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDiaChi.setText("Địa chỉ:");
        lblDiaChi.setPreferredSize(new java.awt.Dimension(100, 25));

        lblTienPhuCapTheoNgay.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTienPhuCapTheoNgay.setText("Tiền phụ cấp ngày:");
        lblTienPhuCapTheoNgay.setPreferredSize(new java.awt.Dimension(154, 25));

        txtTienPhuCapTheoNgay.setEditable(false);
        txtTienPhuCapTheoNgay.setBackground(new java.awt.Color(255, 255, 255));
        txtTienPhuCapTheoNgay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTienPhuCapTheoNgay.setAlignmentY(1.0F);
        txtTienPhuCapTheoNgay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTienPhuCapTheoNgay.setPreferredSize(new java.awt.Dimension(170, 25));
        txtTienPhuCapTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienPhuCapTheoNgayActionPerformed(evt);
            }
        });

        lblTienChuyenCan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTienChuyenCan.setText("Tiền chuyên cần:");
        lblTienChuyenCan.setPreferredSize(new java.awt.Dimension(154, 25));

        txtTienChuyenCan.setEditable(false);
        txtTienChuyenCan.setBackground(new java.awt.Color(255, 255, 255));
        txtTienChuyenCan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTienChuyenCan.setAlignmentY(1.0F);
        txtTienChuyenCan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTienChuyenCan.setPreferredSize(new java.awt.Dimension(170, 25));
        txtTienChuyenCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienChuyenCanActionPerformed(evt);
            }
        });

        lblGhiChu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblGhiChu.setText("Ghi chú:");
        lblGhiChu.setPreferredSize(new java.awt.Dimension(105, 25));

        txtGhiChu.setEditable(false);
        txtGhiChu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGhiChu.setAlignmentY(1.0F);
        txtGhiChu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtGhiChu.setPreferredSize(new java.awt.Dimension(170, 25));
        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pThongTinLayout = new javax.swing.GroupLayout(pThongTin);
        pThongTin.setLayout(pThongTinLayout);
        pThongTinLayout.setHorizontalGroup(
            pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongTinLayout.createSequentialGroup()
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblHoTenNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pThongTinLayout.createSequentialGroup()
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTenNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pThongTinLayout.createSequentialGroup()
                                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pThongTinLayout.createSequentialGroup()
                                        .addComponent(radNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(73, 73, 73)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pThongTinLayout.createSequentialGroup()
                                    .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbbKinhNghiem, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE)
                                        .addComponent(cbbTayNghe, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbbTinhTrang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(pThongTinLayout.createSequentialGroup()
                                    .addComponent(lblTienPhuCapTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTienPhuCapTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pThongTinLayout.createSequentialGroup()
                                    .addComponent(lblTienChuyenCan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTienChuyenCan, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(pThongTinLayout.createSequentialGroup()
                                .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        pThongTinLayout.setVerticalGroup(
            pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongTinLayout.createSequentialGroup()
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pThongTinLayout.createSequentialGroup()
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pThongTinLayout.createSequentialGroup()
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pThongTinLayout.createSequentialGroup()
                                .addComponent(cbbTayNghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbKinhNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pThongTinLayout.createSequentialGroup()
                                .addComponent(lblPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTienPhuCapTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienPhuCapTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTienChuyenCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienChuyenCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(85, 167, 222));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addadd.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(85, 167, 222));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save2.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setEnabled(false);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnNhapLai.setBackground(new java.awt.Color(85, 167, 222));
        btnNhapLai.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnNhapLai.setText("Làm mới");
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(85, 167, 222));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editNS_32px.png"))); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pTongQuanLayout = new javax.swing.GroupLayout(pTongQuan);
        pTongQuan.setLayout(pTongQuanLayout);
        pTongQuanLayout.setHorizontalGroup(
            pTongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTongQuanLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pReload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addComponent(jscrCN)
            .addGroup(pTongQuanLayout.createSequentialGroup()
                .addComponent(pImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTongQuanLayout.createSequentialGroup()
                .addGap(0, 507, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pTongQuanLayout.setVerticalGroup(
            pTongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTongQuanLayout.createSequentialGroup()
                .addGroup(pTongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pReload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscrCN, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pTongQuanLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pQLCongNhanLayout = new javax.swing.GroupLayout(pQLCongNhan);
        pQLCongNhan.setLayout(pQLCongNhanLayout);
        pQLCongNhanLayout.setHorizontalGroup(
            pQLCongNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pQLCongNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pTongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pQLCongNhanLayout.setVerticalGroup(
            pQLCongNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQLCongNhanLayout.createSequentialGroup()
                .addComponent(pTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(685, Short.MAX_VALUE))
            .addGroup(pQLCongNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pQLCongNhanLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(pTongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pQLCongNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pQLCongNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbLocTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLocTinhTrangActionPerformed
        int stt = 1;
        String[] row1 = {"STT", "Mã CN", "Họ tên", "Giới tính", "Ngày sinh", "SĐT", "Địa chỉ", "Tay nghề", "Kinh nghiệm", "Tình trạng", "Ngày vào", "Tiền phụ cấp", "Tiền chuyên cần", "Ghi chú"};
        modelCN = new DefaultTableModel(row1, 0);
        tableCN.setModel(modelCN);
        Boolean testTT = true;
        if (cbbLocTinhTrang.getSelectedIndex() == 1) {
            testTT = false;
        }
        for (CongNhan s : cn_DAO.getAllCongNhan()) {
            if (s.getTinhTrang() == testTT) {
                String phai = "Nam";
                String tinhTrang = "Thôi việc";
                if (!s.getPhai()) {
                    phai = "Nu";
                }
                if (s.getTinhTrang()) {
                    tinhTrang = "Đang làm việc";
                }
                modelCN.addRow(new Object[]{stt, s.getMaCN(), s.getHoTen(), phai, s.getNgaySinh(), s.getSoDT(), s.getDiaChi(), s.getTayNghe(), s.getKinhNghiem(), tinhTrang, s.getNgayVaoLam(), Double.toString(s.getTienPhuCapTheoNgay()), Double.toString(s.getTienChuyenCan()), s.getGhiChu()});
                stt++;
            }
        }
    }//GEN-LAST:event_cbbLocTinhTrangActionPerformed

    private void cbbLocTayNgheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLocTayNgheActionPerformed
        modelCN.setNumRows(0);
        if (cbbLocTayNghe.getSelectedIndex() == 0)
        addListCN();
        else {
            int stt = 1;
            String[] row1 = {"STT", "Mã CN", "Họ tên", "Giới tính", "Ngày sinh", "SĐT", "Địa chỉ", "Tay nghề", "Kinh nghiệm", "Tình trạng", "Ngày vào", "Tiền phụ cấp", "Tiền chuyên cần", "Ghi chú"};
            modelCN = new DefaultTableModel(row1, 0);
            tableCN.setModel(modelCN);
            for (CongNhan s : cn_DAO.getAllCongNhan()) {
                if (s.getTayNghe().equalsIgnoreCase(cbbLocTayNghe.getSelectedItem().toString())) {
                    String phai = "Nam";
                    String tinhTrang = "Thôi việc";
                    if (!s.getPhai()) {
                        phai = "Nu";
                    }
                    if (s.getTinhTrang()) {
                        tinhTrang = "Đang làm việc";
                    }
                    modelCN.addRow(new Object[]{stt, s.getMaCN(), s.getHoTen(), phai, s.getNgaySinh(), s.getSoDT(), s.getDiaChi(), s.getTayNghe(), s.getKinhNghiem(), tinhTrang, s.getNgayVaoLam(), Double.toString(s.getTienPhuCapTheoNgay()), Double.toString(s.getTienChuyenCan()), s.getGhiChu()});
                    stt++;
                }
            }
        }
    }//GEN-LAST:event_cbbLocTayNgheActionPerformed

    private void txtTimCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimCNActionPerformed
        btnTimKiem.doClick();
    }//GEN-LAST:event_txtTimCNActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        modelCN.setNumRows(0);
        int stt = 1;
        String[] row1 = {"STT", "Mã CN", "Họ tên", "Giới tính", "Ngày sinh", "SĐT", "Địa chỉ", "Tay nghề", "Kinh nghiệm", "Tình trạng", "Ngày vào", "Tiền phụ cấp", "Tiền chuyên cần", "Ghi chú"};
        modelCN = new DefaultTableModel(row1, 0);
        tableCN.setModel(modelCN);
        for (CongNhan s : cn_DAO.getAllCongNhan()) {
            if (s.getMaCN().equalsIgnoreCase(txtTimCN.getText())) {
                String phai = "Nam";
                String tinhTrang = "Thôi việc";
                if (!s.getPhai()) {
                    phai = "Nu";
                }
                if (s.getTinhTrang()) {
                    tinhTrang = "Đang làm việc";
                }
                modelCN.addRow(new Object[]{stt, s.getMaCN(), s.getHoTen(), phai, s.getNgaySinh(), s.getSoDT(), s.getDiaChi(), s.getTayNghe(), s.getKinhNghiem(), tinhTrang, s.getNgayVaoLam(), Double.toString(s.getTienPhuCapTheoNgay()), Double.toString(s.getTienChuyenCan()), s.getGhiChu()});
                stt++;
                break;
            } else if (s.getHoTen().equals(txtTimCN.getText())) {
                String phai = "Nam";
                String tinhTrang = "Thôi việc";
                if (!s.getPhai()) {
                    phai = "Nu";
                }
                if (s.getTinhTrang()) {
                    tinhTrang = "Đang làm việc";
                }
                modelCN.addRow(new Object[]{stt, s.getMaCN(), s.getHoTen(), phai, s.getNgaySinh(), s.getSoDT(), s.getDiaChi(), s.getTayNghe(), s.getKinhNghiem(), tinhTrang, s.getNgayVaoLam(), Double.toString(s.getTienPhuCapTheoNgay()), Double.toString(s.getTienChuyenCan()), s.getGhiChu()});
                stt++;
            } else if (s.getSoDT().equals(txtTimCN.getText())) {
                String phai = "Nam";
                String tinhTrang = "Thôi việc";
                if (!s.getPhai()) {
                    phai = "Nu";
                }
                if (s.getTinhTrang()) {
                    tinhTrang = "Đang làm việc";
                }
                modelCN.addRow(new Object[]{stt, s.getMaCN(), s.getHoTen(), phai, s.getNgaySinh(), s.getSoDT(), s.getDiaChi(), s.getTayNghe(), s.getKinhNghiem(), tinhTrang, s.getNgayVaoLam(), Double.toString(s.getTienPhuCapTheoNgay()), Double.toString(s.getTienChuyenCan()), s.getGhiChu()});
                stt++;
                break;
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        cbbLocTayNghe.setSelectedIndex(0);
        cbbLocTinhTrang.setSelectedIndex(0);
        addListCN();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void tableCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCNMouseClicked
        int row = tableCN.getSelectedRow();
        txtMaNV.setText(modelCN.getValueAt(row, 1).toString());
        txtHoTenNV.setText(modelCN.getValueAt(row, 2).toString());
        if (modelCN.getValueAt(row, 3).toString().equals("Nam")) {
            radNam.setSelected(true);
        } else {
            radNu.setSelected(true);
        }
        dateNgaySinh.setDate((Date) modelCN.getValueAt(row, 4));
        txtSDT.setText(modelCN.getValueAt(row, 5).toString());
        txtDiaChi.setText(modelCN.getValueAt(row, 6).toString());
        cbbTayNghe.setSelectedItem(modelCN.getValueAt(row, 7).toString());
        cbbKinhNghiem.setSelectedIndex(2);
        cbbKinhNghiem.setSelectedItem(modelCN.getValueAt(row, 8).toString());
        cbbTinhTrang.setSelectedItem(modelCN.getValueAt(row, 9).toString());
        dateNgayVaoLam.setDate((Date) modelCN.getValueAt(row, 10));
        txtTienPhuCapTheoNgay.setText(modelCN.getValueAt(row, 11).toString());
        txtTienChuyenCan.setText(modelCN.getValueAt(row, 12).toString());
        txtGhiChu.setText(modelCN.getValueAt(row, 13).toString());

        CongNhan cn = cn_DAO.getCongNhanTheoMa(txtMaNV.getText());
        lbHinhCN.setIcon(new ImageIcon(getClass().getResource(cn.getHinhAnh())));
    }//GEN-LAST:event_tableCNMouseClicked

    private void tableCNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCNKeyReleased
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_UP || keyCode == KeyEvent.VK_DOWN) {
            int row = tableCN.getSelectedRow();
            txtMaNV.setText(modelCN.getValueAt(row, 1).toString());
            txtHoTenNV.setText(modelCN.getValueAt(row, 2).toString());
            if (modelCN.getValueAt(row, 3).toString().equals("Nam")) {
                radNam.setSelected(true);
            } else {
                radNu.setSelected(true);
            }
            dateNgaySinh.setDate((Date) modelCN.getValueAt(row, 4));
            txtSDT.setText(modelCN.getValueAt(row, 5).toString());
            txtDiaChi.setText(modelCN.getValueAt(row, 6).toString());
            cbbTayNghe.setSelectedItem(modelCN.getValueAt(row, 7).toString());
            cbbKinhNghiem.setSelectedIndex(2);
            cbbKinhNghiem.setSelectedItem(modelCN.getValueAt(row, 8).toString());
            cbbTinhTrang.setSelectedItem(modelCN.getValueAt(row, 9).toString());
            dateNgayVaoLam.setDate((Date) modelCN.getValueAt(row, 10));
            txtTienPhuCapTheoNgay.setText(modelCN.getValueAt(row, 11).toString());
            txtTienChuyenCan.setText(modelCN.getValueAt(row, 12).toString());
            txtGhiChu.setText(modelCN.getValueAt(row, 13).toString());

            CongNhan cn = cn_DAO.getCongNhanTheoMa(txtMaNV.getText());
            lbHinhCN.setIcon(new ImageIcon(getClass().getResource(cn.getHinhAnh())));
        }
    }//GEN-LAST:event_tableCNKeyReleased

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        JFileChooser fileChooser = new JFileChooser("src//image");
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("image", "jpg", "png"); // định dạng hình ảnh được chọn
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false); // 1 thời điểm người dùng chỉ được chọn 1 hình ảnh.

        fileChooser.setDialogTitle("Chọn hình ảnh");
        int x = fileChooser.showDialog(this, "Chọn");
        if (x == JFileChooser.APPROVE_OPTION) {
            File ftenAnh = fileChooser.getSelectedFile();
            String duongdanAnh = ftenAnh.getAbsolutePath();
            hinhAnh = duongdanAnh.substring(76).replace('\\', '/');
            lbHinhCN.setIcon(resizeImage(duongdanAnh));
            System.out.println(hinhAnh);

        }
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtHoTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenNVActionPerformed

    private void radNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNamActionPerformed

    private void radNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNuActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void cbbTayNgheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTayNgheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTayNgheActionPerformed

    private void cbbKinhNghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKinhNghiemActionPerformed
        int phuCapInt = 2000+cbbKinhNghiem.getSelectedIndex()*5000;
        txtTienPhuCapTheoNgay.setText(Integer.toString(phuCapInt));
        int chuyenCanInt = 200000+ cbbKinhNghiem.getSelectedIndex()*100000;
        txtTienChuyenCan.setText(Integer.toString(chuyenCanInt));
    }//GEN-LAST:event_cbbKinhNghiemActionPerformed

    private void txtTienPhuCapTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienPhuCapTheoNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienPhuCapTheoNgayActionPerformed

    private void txtTienChuyenCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienChuyenCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienChuyenCanActionPerformed

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (btnThem.getText().equals("Thêm")) {
            nhapLai();
            txtMaNV.setText(cn_DAO.getMaCN());
            txtHoTenNV.setEditable(true);
            radNam.setEnabled(true);
            radNu.setEnabled(true);
            txtSDT.setEditable(true);
            txtDiaChi.setEditable(true);
            cbbTayNghe.setEnabled(true);
            cbbTayNghe.setSelectedIndex(0);
            cbbKinhNghiem.setEnabled(true);
            cbbKinhNghiem.setSelectedIndex(0);
            cbbTinhTrang.setEnabled(true);
            cbbTinhTrang.setSelectedIndex(0);
            txtTienPhuCapTheoNgay.setEditable(true);
            txtTienChuyenCan.setEditable(true);
            txtGhiChu.setEditable(true);
            txtGhiChu.setText("không");

            txtHoTenNV.requestFocus();
            btnThem.setText("Hủy");
            btnLuu.setEnabled(true);
            btnUpdate.setEnabled(false);
            btnChonAnh.setEnabled(true);
        } else {
            nhapLai();
            txtHoTenNV.setEditable(false);
            txtHoTenNV.setEditable(false);
            radNam.setEnabled(false);
            radNu.setEnabled(false);
            txtSDT.setEditable(false);
            txtDiaChi.setEditable(false);
            cbbTayNghe.setEnabled(false);
            cbbTayNghe.setSelectedIndex(0);
            cbbKinhNghiem.setEnabled(false);
            cbbKinhNghiem.setSelectedIndex(0);
            cbbTinhTrang.setEnabled(false);
            cbbTinhTrang.setSelectedIndex(0);
            txtTienPhuCapTheoNgay.setEditable(false);
            txtTienChuyenCan.setEditable(false);
            txtGhiChu.setEnabled(false);
            txtHoTenNV.requestFocus();
            btnThem.setText("Thêm");
            btnLuu.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnChonAnh.setEnabled(false);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            String hoTen = txtHoTenNV.getText();
            boolean gioiTinh = radNam.isSelected();
            String soDT = txtSDT.getText();
            String diaChi = txtDiaChi.getText();
            String tinhTrang = cbbTinhTrang.getSelectedItem().toString();
            boolean tTrang = Boolean.parseBoolean(tinhTrang);
            if (tinhTrang.equalsIgnoreCase("Đang làm việc")) {
                tTrang = true;
            }
            String kinhNghiem = cbbKinhNghiem.getSelectedItem().toString();

            double phuCap = Double.parseDouble(txtTienPhuCapTheoNgay.getText().toString());
            double chuyenCan = Double.parseDouble(txtTienChuyenCan.getText().toString());

            String tayNghe = cbbTayNghe.getSelectedItem().toString();

            String ghiChu = txtGhiChu.getText();
            Date now = new Date(System.currentTimeMillis());
            int namHienTai = now.getYear();
            int namSinh = dateNgaySinh.getDate().getYear();
            int thangSinh = dateNgaySinh.getDate().getMonth();
            int ngaySinh = dateNgaySinh.getDate().getDate();

            int namVaoLam = dateNgayVaoLam.getDate().getYear();
            int thangVaoLam = dateNgayVaoLam.getDate().getMonth();
            int ngayVaoLam = dateNgayVaoLam.getDate().getDate();

            if (btnThem.getText().equals("Hủy")) {
                String maCN = cn_DAO.getMaCN();
                if (validDataCongNhan(txtHoTenNV, txtSDT, txtDiaChi)) {
                    if (namHienTai - namSinh >= 18) {
                        //                            if (ngayVaoLam1.getTime() <= now.getTime()) {
                            if (cn_DAO.checkSdtCN(soDT) == false) {
                                CongNhan cn = new CongNhan(maCN, hoTen, gioiTinh, new Date(namSinh, thangSinh, ngaySinh), soDT, diaChi, tTrang, now, hinhAnh, tayNghe, kinhNghiem, phuCap, chuyenCan, ghiChu);
                                if (cn_DAO.createCongNhan(cn)) {
                                    addListCN();
                                    JOptionPane.showMessageDialog(this, "Thêm công nhân thành công");
                                    nhapLai();
                                } else {
                                    JOptionPane.showMessageDialog(this, "Thêm công nhân thất bại");
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại \nVui lòng nhập lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                                txtSDT.requestFocus();
                                txtSDT.selectAll();
                            }
                            //                            } else {
                            //                                JOptionPane.showMessageDialog(this, "Ngày vào làm không hợp lệ\nNgày vào làm phải nhỏ hơn hoặc bằng ngày hiện tại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                            //                                dateNgayVaoLam.requestFocus();
                            //                            }
                    } else {
                        JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ\ncông nhân phải từ đủ 18 tuổi.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                        dateNgaySinh.requestFocus();
                    }
                }

            } else if (btnUpdate.getText().equals("Hủy")) {
                int thongBao = JOptionPane.showConfirmDialog(this, "Vui lòng nhấn Xác nhận để cập nhật thông tin nhân viên này.",
                    "Thông báo xác nhận", JOptionPane.YES_NO_OPTION);
                if (thongBao == JOptionPane.YES_OPTION) {
                    String maCN = txtMaNV.getText();
                    if (validDataCongNhan(txtHoTenNV, txtSDT, txtDiaChi)) {
                        if (namHienTai - namSinh >= 18) {
                            //                            if (ngayVaoLam1.getTime() <= now.getTime()) {
                                //                                if (nvhcDAO.checkSdtNV(soDT) == false) {
                                    CongNhan cn = new CongNhan(maCN, hoTen, gioiTinh, new Date(namSinh, thangSinh, ngaySinh), soDT, diaChi, tTrang, now, hinhAnh, tayNghe, kinhNghiem, phuCap, chuyenCan, ghiChu);
                                    if (cn_DAO.createCongNhan(cn)) {
                                        addListCN();
                                        JOptionPane.showMessageDialog(this, "Cập nhật công nhân thành công");
                                        nhapLai();
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Cập nhật công nhân thất bại");
                                    }
                                    //                                } else {
                                    //                                    JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại \nVui lòng nhập lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                                    //                                    txtSDT.requestFocus();
                                    //                                    txtSDT.selectAll();
                                    //                                }
                                //                            } else {
                                //                                JOptionPane.showMessageDialog(this, "Ngày vào làm không hợp lệ\nNgày vào làm phải nhỏ hơn hoặc bằng ngày hiện tại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                                //                                dateNgayVaoLam.requestFocus();
                                //                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ\nNhân viên phải từ đủ 18 tuổi.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                            dateNgaySinh.requestFocus();
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin công nhân", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        nhapLai();
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (btnUpdate.getText().equals("Cập nhật")) {
            int row = tableCN.getSelectedRow();
            if (row >= 0) {
                txtHoTenNV.setEditable(true);
                radNam.setEnabled(true);
                radNu.setEnabled(true);
                txtSDT.setEditable(true);
                txtDiaChi.setEditable(true);
                txtTienPhuCapTheoNgay.setEditable(true);
                txtTienChuyenCan.setEditable(true);
                cbbKinhNghiem.setEnabled(true);
                cbbTayNghe.setEnabled(true);
                cbbTinhTrang.setEnabled(true);
                txtGhiChu.setEditable(true);

                txtHoTenNV.requestFocus();
                btnUpdate.setText("Hủy");
                btnLuu.setEnabled(true);
                btnThem.setEnabled(false);
                btnChonAnh.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần cập nhật thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            nhapLai();
            txtHoTenNV.setEditable(false);
            radNam.setEnabled(false);
            radNu.setEnabled(false);
            txtSDT.setEditable(false);
            txtDiaChi.setEditable(false);
            txtTienPhuCapTheoNgay.setEditable(true);
            txtTienChuyenCan.setEditable(true);
            cbbKinhNghiem.setEnabled(true);
            cbbTayNghe.setEnabled(true);
            cbbTinhTrang.setEnabled(true);
            txtGhiChu.setEditable(true);

            btnUpdate.setText("Cập nhật");
            btnLuu.setEnabled(false);
            btnThem.setEnabled(true);
            btnChonAnh.setEnabled(false);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtTimCNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimCNFocusGained
        txtTimCN.setText("");
        txtTimCN.setForeground( Color.BLACK);
    }//GEN-LAST:event_txtTimCNFocusGained

    private void txtTimCNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimCNFocusLost
        if (txtTimCN.getText().equals("")) {
           txtTimCN.setText("Tìm kiếm");
           txtTimCN.setForeground(new Color(204, 204, 204));
       } else {
           txtTimCN.setForeground( Color.BLACK);
       }
    }//GEN-LAST:event_txtTimCNFocusLost
    private ImageIcon resizeImage(String imagePath) {
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lbHinhCN.getWidth(), lbHinhCN.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private void nhapLai() {
        txtMaNV.setText("");
        txtHoTenNV.setText("");
        txtSDT.setText("");
        txtDiaChi.setText("");
        txtTienPhuCapTheoNgay.setText("");
        txtTienChuyenCan.setText("");
        txtTienPhuCapTheoNgay.setText("");
        txtGhiChu.setText("");
        radNam.setSelected(true);
        cbbTinhTrang.setSelectedItem("Đang làm việc");

        txtHoTenNV.requestFocus();
    }

    private void addListCN() {
        int stt = 1;
        String[] row1 = {"STT", "Mã CN", "Họ tên", "Giới tính", "Ngày sinh", "SĐT", "Địa chỉ", "Tay nghề", "Kinh nghiệm", "Tình trạng", "Ngày vào", "Tiền phụ cấp", "Tiền chuyên cần", "Ghi chú"};
        modelCN = new DefaultTableModel(row1, 0);
        tableCN.setModel(modelCN);
        for (CongNhan s : cn_DAO.getAllCongNhan()) {
            String phai = "Nam";
            String tinhTrang = "Thôi việc";
            if (!s.getPhai()) {
                phai = "Nu";
            }
            if (s.getTinhTrang()) {
                tinhTrang = "Đang làm việc";
            }
            modelCN.addRow(new Object[]{stt, s.getMaCN(), s.getHoTen(), phai, s.getNgaySinh(), s.getSoDT(), s.getDiaChi(), s.getTayNghe(), s.getKinhNghiem(), tinhTrang, s.getNgayVaoLam(), Double.toString(s.getTienPhuCapTheoNgay()), Double.toString(s.getTienChuyenCan()), s.getGhiChu()});
            stt++;
        }
    }    public boolean validDataCongNhan(JTextField txtHoTen, JTextField txtSDT, JTextField txtDiaChi) {
        String hoTen = txtHoTen.getText().trim();
        String soDT = txtSDT.getText().trim();
        String diaChi = txtDiaChi.getText().trim();

        if (!(hoTen.length() > 0 && hoTen.matches("^([ A-Za-za-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]*(\\s?))+$"))) {
            JOptionPane.showMessageDialog(null, "Họ tên không hợp lệ \nVui lòng nhập họ tên theo mẫu: Lê Văn A", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtHoTen.requestFocus();
            return false;
        }

        if (!(soDT.length() > 0 && soDT.matches("^(03|08|09|07|05)[0-9]{8}$"))) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ \nSDT gồm 10 chữ số, bắt đầu bằng 2 chữ số: 03, 08, 07, 09, 05", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtSDT.requestFocus();
            return false;
        }

        if (!(diaChi.length() > 0 && diaChi.matches("^([ A-Za-z0-9,\\/.a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]*(\\s?))+$"))) {
            JOptionPane.showMessageDialog(null, "Địa chỉ không hợp lệ \nVui lòng nhập địa chỉ theo mẫu: 1428 Huỳnh Tấn Phát, Phú Mỹ, Quận 7", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtDiaChi.requestFocus();
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbKinhNghiem;
    private javax.swing.JComboBox<String> cbbLocTayNghe;
    private javax.swing.JComboBox<String> cbbLocTinhTrang;
    private javax.swing.JComboBox<String> cbbTayNghe;
    private javax.swing.JComboBox<String> cbbTinhTrang;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private com.toedter.calendar.JDateChooser dateNgayVaoLam;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jscrCN;
    private javax.swing.JLabel lbHinhCN;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblHoTenNV;
    private javax.swing.JLabel lblLuongCB;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblPhai;
    private javax.swing.JLabel lblPhongBan;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTienChuyenCan;
    private javax.swing.JLabel lblTienPhuCapTheoNgay;
    private javax.swing.JPanel pImage;
    private javax.swing.JPanel pQLCongNhan;
    private javax.swing.JPanel pReload;
    private javax.swing.JPanel pThongTin;
    private javax.swing.JPanel pTittle;
    private javax.swing.JPanel pTongQuan;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTable tableCN;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTenNV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTienChuyenCan;
    private javax.swing.JTextField txtTienPhuCapTheoNgay;
    private javax.swing.JTextField txtTimCN;
    // End of variables declaration//GEN-END:variables
}
